// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwuojohdgetvacqyhbaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dW9qb2hkZ2V0dmFjcXloYmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMDE1MzgsImV4cCI6MjA1MjU3NzUzOH0.h0FZyOxIN9nIWA126y1dT_pk_LyosAOV5HZLAD6knso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);